### ISSUE TITLE
Offline EKS-anywhere installation

### ISSUE THREAD

**Issue by jgan129** [aws/eks-anywhere#1075]
**What would you like to be added**:
A way to be able to install eks-anywhere cluster without Internet connection.

**Why is this needed**:
There are customers that do not allow Internet connection during a cluster's installation. It would be useful in such cases if there was a way to download any artifacts/resources needed in "offline" repositories and proceed with the eks cluster setup without the need of external (Internet) connection.

**Comment by TerryHowe** [comment]
In v0.6.0 there is support for private registries https://anywhere.eks.amazonaws.com/docs/reference/clusterspec/registrymirror/

**Comment by jgan129** [comment]
According to documentation it appears there are more network endpoints requiring Internet access. Are these covered by using private registries?

_"The administrative machine and the target workload environment will need network access to:

public.ecr.aws
anywhere-assets.eks.amazonaws.com (to download the EKS Anywhere binaries, manifests and OVAs)
distro.eks.amazonaws.com (to download EKS Distro binaries and manifests)
d2glxqk2uabbnd.cloudfront.net (for EKS Anywhere and EKS Distro ECR container images)
api.github.com (only if GitOps is enabled)"_

https://anywhere.eks.amazonaws.com/docs/reference/vsphere/vsphere-prereq/

**Comment by abhinavmpandey08** [comment]
Currently, EKS-A can not be installed in a completely disconnected air-gapped environment. The private registry support allows for pulling from a private registry instead of public.ecr.aws but there are still some other things that need internet access, especially different manifests.

To get around that, we also support Proxy configuration for your cluster to pull these manifests https://anywhere.eks.amazonaws.com/docs/reference/clusterspec/proxy/

That said, air gap support is on our radar and we have an open issue to track it as well https://github.com/aws/eks-anywhere/issues/150

**Comment by jgan129** [comment]
> Currently, EKS-A can not be installed in a completely disconnected air-gapped environment. The private registry support allows for pulling from a private registry instead of public.ecr.aws but there are still some other things that need internet access, especially different manifests.
> 
> To get around that, we also support Proxy configuration for your cluster to pull these manifests https://anywhere.eks.amazonaws.com/docs/reference/clusterspec/proxy/
> 
> That said, air gap support is on our radar and we have an open issue to track it as well #150

Thanks @abhinavmpandey08 
Issue #150  looks like being a similar one which covers this need.
