### ISSUE TITLE
EKSA kind kube-vip service not accessible

### ISSUE THREAD

**Issue by madhu-liferay** [aws/eks-anywhere#1201]
Hi all, I have setup EKSA loca cluster as per https://anywhere.eks.amazonaws.com/docs/getting-started/local-environment/ which is working fine.

I have further setup kube-vip LB as per https://anywhere.eks.amazonaws.com/docs/tasks/workload/loadbalance/kubevip/arp/

I am not able to connect using the service's EXTERNAL-IP. Able to connect using that IP from inside the pod though - screenschot here https://paste.pics/FW5HD

Had posted in the forum earlier https://repost.aws/questions/QUjkWkMt0WQYydJNqQmIPpcA/eksa-kind-kube-vip-service-not-accessible

**Comment by TerryHowe** [comment]
I don't recall hearing about repost, sorry I don't think that is monitored.

It looks like the load balancer is working, you are getting the IP and it is reachable inside. There are better people out there for diagnosing network issues, but it sounds like routing to that load balancer is not working from where ever you are trying to reach it. You didn't mention anything about your network architecture, but from the machine you are trying to access your cluster. For example:

```
route get 192.168.0.230
```

For example on my machine accessing my kube-vip IP I can see it routes over the right interface `utun2`:
```
% route get 198.18.100.79
   route to: 198.18.100.79
destination: 198.18.0.0
       mask: 255.254.0.0
  interface: utun2
      flags: <UP,DONE,STATIC,PRCLONING>
 recvpipe  sendpipe  ssthresh  rtt,msec    rttvar  hopcount      mtu     expire
       0         0         0         0         0         0      1420         0 
```

Is your LB IP range in the same range/routing as your control plane IP?

**Comment by abhinavmpandey08** [comment]
The docker provider internally uses [KinD](https://kind.sigs.k8s.io/) which creates a virtual docker network for its networking. `kube-vip` also assigns the LB IP in this local network which can be reached from within the host running KinD itself but not from the outside. This is because external devices won't have a route to reach this virtual network.

To test `kube-vip` with externally accessible service IPs, I would recommend [creating a cluster on vSphere](https://anywhere.eks.amazonaws.com/docs/getting-started/production-environment/).
