### ISSUE TITLE
Update the Flux CLI and controller images on ECR

### ISSUE THREAD

**Issue by stefanprodan** [aws/eks-anywhere#143]
**What would you like to be added**:

Hi team, I've noticed that the Flux container images used by EKS Anywhere are being pushed to ECR. The Flux images are behind the upstream distribution (critical bugs where fixed and new features were added).

Can you please update the Flux images on the Public ECR and the Flux binary included in EKS Anywhere?

Is there a public repo with the build script? if so I could update them myself. 

**Why is this needed**:

It would be great if EKS Anywhere would be in sync with the latest stable Flux release.

```console
$ flux -v
  flux version 0.17.0

$ flux install --export | grep ghcr
  image: ghcr.io/fluxcd/helm-controller:v0.11.2
  image: ghcr.io/fluxcd/kustomize-controller:v0.14.0
  image: ghcr.io/fluxcd/notification-controller:v0.16.0
  image: ghcr.io/fluxcd/source-controller:v0.15.4
```

**Comment by jaxesn** [comment]
Thanks @stefanprodan! The repo we use to manage the build scripts and versions of our dependencies is https://github.com/aws/eks-anywhere-build-tooling. Well write up some docs for future reference for people.

As a general answer, and sort of a draft for an official versioning policy, we won't always be in sync with upstream latest versions. Our goal is to provide a solution with a version set of dependencies which all work together vs always being on the latest. Most of our dependencies come from CAPI and unless we have good reason to deviate well probably shoot to match upstream there. In the specific case of Flux, we do have a bit more leeway here since it's more like "addon" and what version we use is more just about our code being compatible.

**Comment by TerryHowe** [comment]
I put this on the oncall milestone, but it should be next or next+1 probably
