### ISSUE TITLE
Support Macs with Apple Silicon and arm processors

### ISSUE THREAD

**Issue by rothgar** [aws/eks-anywhere#182]
**What would you like to be added**:
Currently the bootstrap cluster and clusters using the docker provider cannot run on M1 Macs. It would be good to support these options for administrative machines and local clusters.

**Why is this needed**:
To allow more users to try EKS-A and manage clusters.

**Comment by neurostream** [comment]
### Why our shop likes watching this issue...

- For local offline development workstations, we started to replace the container engine bundled with Docker Desktop and it's Docker.raw image from docker.com with containerd on Amazon Linux 2 KVM and it's QCOW2 images from amazonlinux.com.
  - For legacy amd64 workstations we use the[ amd64 image](https://cdn.amazonlinux.com/os-images/2.0.20211201.0/kvm/amzn2-kvm-2.0.20211201.0-x86_64.xfs.gpt.qcow2).
  - For new arm64 workstations we use the [arm64 image ](https://cdn.amazonlinux.com/os-images/2.0.20211201.0/kvm-arm64/amzn2-kvm-2.0.20211201.0-arm64.xfs.gpt.qcow2)
- This has strengthened the local to remote environment parity experienced by developers for basic container image development.

- However, if a developer is running a local k8s stack (say, _minikube_ , _k3s_ , etc. ) that is different from production/hosted environments, then there are still opportunities to further improve local-to-remote environment parity at the k8s level.  So, the next stop on that road for us is standardizing Kubernetes layer as EKS for container orchestration (and not just within the AWS Cloud).
  - Our developers use Macs, and Apple Silicon/arm64 has already replaced Intel/amd64 Macs for local development workstations.
  - _**In order for local offline development to drive the transition of cloud/hosted compute from amd64 to arm64, we see EKS-A support for arm64 as key to success in that effort**_ - using the Container provider (is that based on KIND?) instead of the VMWare OVA provider.
  - We considered starting off from the VMware angle, but, at the moment:
    -  the roadmap and timeline with VMWare Fusion for Apple Silicon is not clear right now, still being a work-in-progress under VMWare's private beta for Fusion on new Macs.
    -  EKS-A's VMWare provider is specifically cited for use with vSphere (and so not a solution for running EKS on Fusion/Workstation )
    -  qemu-kvm linux instances running containerd is just generally popular with our developers, so we haven't really missed the vmware.com or docker.com footprint in our tool chains.

This is all with the pre-supposition that moving to aarch64/arm64 from amd64 for our remote/hosted EKS environments is a "good thing" - which, for our requirements, that is very much the case.

**Comment by Pablo-platypus** [comment]
any update on this? is it in the roadmap? any time estimates?

**Comment by ycyr** [comment]
Any news on this issue?

**Comment by rothgar** [comment]
Would it be ok to update the homebrew formula to install the correct binary on M1 Macs?

**Comment by mikejennings** [comment]
Please?

**Comment by DaveInga** [comment]
Any update on this?

**Comment by soostdijck** [comment]
Curious what the status is here, my intel mac will be replaced in a couple of months. I would love a M1/2 option on brew.

**Comment by RazaGR** [comment]
does it work now?

**Comment by chrisdoherty4** [comment]
> does it work on M2?

Yes.

**Comment by RazaGR** [comment]
> > does it work on M2?
> 
> Yes.

when I installed using `brew install aws/tap/ens-anywhere `
I get this warning
```
=====WARNING=====
ARM CPU's are not yet supported.
The amd64 binary has been installed but will not work.
Please uninstall this formula.
```

**Comment by chrisdoherty4** [comment]
@RazaGR There was a delay publishing the 0.18.1 brew formula, but the latest installs ARM binaries.

**Comment by RazaGR** [comment]
@chrisdoherty4 confirm it works with new formula, I have updated the docs to reflect this as that was confusing for me.
https://github.com/aws/eks-anywhere/pull/7067

Thanks
