### ISSUE TITLE
Run E2E tests from release branch

### ISSUE THREAD

**Issue by g-gaston** [aws/eks-anywhere#322]
When releasing new patch versions for a certain minor cli release, we need the ability to run E2E tests from that minor version release branch.

**Comment by danbudris** [comment]
### status update:
status: in progress.

Created release branch specific codepipelines which:
- build the source from the release branch.
- execute the e2e test suite, using the binary built from the release branch, specifying a bundle override corresponding to the bundle used by the release branch.
- these are created for `release-0.6` and `release-0.5`; set up infrastructure so that creation of additional release branch pipelines is as simple as adding a branch name to an array.

Currently working out kinks in the release branch test executions. Most recently:
- updated the 'delete' command to accept a 'bundles-override' flag, so that we can override the default bundle when calling 'delete cluster' on a release-branch pipeline; without the bundle override, chaos ensues
- working through failures and determining if they're related to the infra, the configuration of the tests, or actual bugs; triaging as I go

**Comment by danbudris** [comment]
Release branch testing is in-place and working as expected.

**Comment by danbudris** [comment]
https://github.com/aws/eks-anywhere/issues/551
