### ISSUE TITLE
Follow up items from Nutanix provider implementation (#3291)

### ISSUE THREAD

**Issue by abhinavmpandey08** [aws/eks-anywhere#3643]
Follow-up items from #3291
- [x] Allow insecure to be configurable https://github.com/aws/eks-anywhere/pull/3291#discussion_r977231477, https://github.com/aws/eks-anywhere/pull/3291#discussion_r982741478
- [x] Base64 encode creds when applying https://github.com/aws/eks-anywhere/pull/3291#discussion_r977234524
- [ ] Enable Kubernetes audit logs using apiServer extraArgs. Here's a reference https://github.com/aws/eks-anywhere/blob/main/pkg/providers/vsphere/config/template-cp.yaml#L133-L159

**Comment by thunderboltsid** [comment]
1. The `insecure` is already configurable but based on whether `AdditionalTrustBundle` is populated or not. The goal here is to remove `insecure` entirely and propagate `AdditionalTrustBundle` to CAPX. However, CAPX does not have that as a parameter so that needs to be addressed on CAPX first.
2. We are planning on swapping out the format of the credentials entirely and that would take care of base64 encoding too.
3. Interesting, will look into it and create another PR.

**Comment by thunderboltsid** [comment]
PR to update the credentials format - https://github.com/aws/eks-anywhere/pull/3669

**Comment by jiayiwang7** [comment]
Feature will be included in EKS-A v0.18.4 release.
