### ISSUE TITLE
Disable embedded cert-manager

### ISSUE THREAD

**Issue by romancin** [aws/eks-anywhere#4719]
**What would you like to be added**:

Currently, although curated packages cannot be used as I don't have enterprise support, an old cert-manager is installed in EKS-A clusters. I would have an option to disable installation of it.

**Why is this needed**:

I want to manage my cluster fully using GitOps. Currently, i need to delete cert-manager completely manually, and then install cert-manager using flux helmrelease. I want to avoid completely manual operations after installing EKS-A. Also, I can use latest cert-manager version (the included version of cert-manager is older than the current one).

**Comment by TerryHowe** [comment]
EKS Anywhere uses Cluster API and Cluster API uses cert-manager, so we cannot disable it for the management cluster. I definitely wouldn't recommend uninstalling it or upgrading it, because we would try to revert that during an upgrade.

My general recommendation would be create a small management cluster and leave it as is and then create workload clusters using that management cluster and do with what you like to the workload clusters. Here are the docs for vSphere for example https://anywhere.eks.amazonaws.com/docs/getting-started/production-environment/vsphere-getstarted/#create-separate-workload-clusters

**Comment by romancin** [comment]
Didn’t tought about that possibility, thank you very much! I tried it and the workload cluster is completely clean, awesome :D

One more question. I am really constrained in resources, so, can the management cluster be completely shutdown and the workload cluster will work without it? It would be necessary only to make upgrades or making changes over workload clusters?

Thank you very much for your help, really appreciate it.

**Comment by pokearu** [comment]
Hi @romancin, we do not recommend shutting down the management cluster.

But technically the workload cluster can run independently, but any gitops or upgrade features that eks-a clusters support all live on the management cluster. So if you would like to use GitOps for any modifications on the workload you would need the management up and active.

**Comment by TerryHowe** [comment]
The management cluster can be very small.

Please reopen if you have anything else
