### ISSUE TITLE
Support using custom CNI

### ISSUE THREAD

**Issue by jiayiwang7** [aws/eks-anywhere#5217]
Sometimes user needs to use its own preferred CNI solution instead of EKS-A Cilium. It would be ideal if EKS-A can provide the possibility to swap out the default CNI with custom one, and EKS-A shall not revert the CNI changes made by the user during CLI upgrade / controller reconciliation.

In terms of solution, there are 2 routes we can go:
1. add a `CustomCNI` field in `ClusterNetwork` where we apply the CNI manifests user input during create/upgrade workflow.
2. add a `UserManaged` field in `ClusterNetwork` indicating user is managing its own CNI. During cluster creation, we still install the default EKS-A Cilium CNI to guarantee the successful provision of the cluster. After the cluster is running, user can update the `ClusterNetwork` with `UserManaged` true, manually delete the default EKS-A Cilium CNI and install custom CNI. Whenever the `UserManaged` flag is presented, the EKS-A CLI upgrade and EKS-A controller will skip updating/applying Cilium components.

 We shall go with option 2 first, as option 1 is hard to validate and test given all the open options that exposes to the user. Also different CNI needs to be installed in various way, some of which cannot be set up properly with single manifest apply. The workflow to support it can be less trivial.

**Comment by Cajga** [comment]
Hi @jiayiwang7, @chrisdoherty4,

Thanks a lot for working on this feature. We were really happy when we saw this listed in the release notes.

We just want to cross check: did all the necessary commits made it to the v.0.15.0 release?

If we check the [list the commits since the last release (v.0.15.1)](https://github.com/aws/eks-anywhere/compare/v0.15.1...main) there seems to be still some commits related to this change:
* [Add Cilium skipUpgrade flag to v1alpha1 API (](https://github.com/aws/eks-anywhere/commit/32dd16e6c0cc5219271d0ec95d8bf025015079a4)https://github.com/aws/eks-anywhere/pull/5298[)](https://github.com/aws/eks-anywhere/commit/32dd16e6c0cc5219271d0ec95d8bf025015079a4)
* [Add Cilium skipUpgrade flag to v1alpha1 API (](https://github.com/aws/eks-anywhere/commit/32dd16e6c0cc5219271d0ec95d8bf025015079a4)https://github.com/aws/eks-anywhere/pull/5298[)](https://github.com/aws/eks-anywhere/commit/32dd16e6c0cc5219271d0ec95d8bf025015079a4)
* [Implement unmanaged CNI for CLI based clusters (](https://github.com/aws/eks-anywhere/commit/ba3bf74b203087ea6d0fc17957b21279b996e0d8)https://github.com/aws/eks-anywhere/pull/5305[)](https://github.com/aws/eks-anywhere/commit/ba3bf74b203087ea6d0fc17957b21279b996e0d8)

Also note: For all of these PR-s the milestone is still set to v0.15.0...

**Comment by chrisdoherty4** [comment]
Hi @Cajga. I've been out the last few weeks so hadn't seen your message. I'll get back to you soon.

**Comment by chrisdoherty4** [comment]
@Cajga, the commits were squashed into a single commit as seen in https://github.com/aws/eks-anywhere/pull/5366/commits, or cherry-picked so you won't see the commits from main.

We'll reflect on our process to make identifying commits in release branches easier in the future.

**Comment by Cajga** [comment]
Hi @chrisdoherty4 ,

Thanks for confirming it.

I was trying to figure it out myself but was not 100% sure what was happening.
